\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{cv-fr}

\LoadClass{cv}

\renewcommand{\ttdefault}{pcr}
\renewcommand{\rmdefault}{ptm}
%\renewcommand{\rmdefault}{phv}
\renewcommand{\sfdefault}{phv}
\newlength{\espaceChamps}
\setlength{\espaceChamps}{1mm}

% Input directory
\newcommand{\educationdir}{french/education}
\newcommand{\experiencedir}{french/experience}
\newcommand{\skilldir}{french/skill}

% Variable
\newlength{\firstcolumnwidth}%
\setlength{\firstcolumnwidth}{2.5cm}%
